import type { Detection, PipelineItem } from '../types'

const partners = [
  'Accenture',
  'Infosys',
  'Wipro',
  'HCL Technologies',
  'TCS',
  'Capgemini',
  'Deloitte',
  'KPMG',
]

const accounts = [
  'Contoso Ltd',
  'Fabrikam Inc',
  'Northwind Traders',
  'Adventure Works',
  'Woodgrove Bank',
  'Tailspin Toys',
  'Litware Inc',
  'Proseware Inc',
]

const solutionAreas = [
  'Azure Infrastructure',
  'Modern Work',
  'Security',
  'Business Applications',
  'Data & AI',
]

const sources: ('email' | 'chat' | 'meeting' | 'multiple')[] = [
  'email',
  'chat',
  'meeting',
  'multiple',
]

export function generateDetections(): Detection[] {
  return [
    {
      id: '1',
      source: 'email',
      confidence: 92,
      title: 'Co-sell discussion with Accenture on Azure Migration for Contoso',
      date: 'April 18, 2025',
      account: 'Contoso Ltd',
      partner: 'Accenture',
      revenue: '$1,200,000',
      explanation:
        'Email thread with j.smith@accenture.com discussing joint proposal for Azure cloud migration. Partner mentioned deploying consultants in Q3.',
      tag: 'new-opportunity',
      status: 'active',
    },
    {
      id: '2',
      source: 'chat',
      confidence: 85,
      title: 'Teams chat about Infosys partnership on Fabrikam security project',
      date: 'April 16, 2025',
      account: 'Fabrikam Inc',
      partner: 'Infosys',
      revenue: '$850,000',
      explanation:
        'Chat conversation mentioning Infosys security practice and their involvement in Fabrikam compliance initiative.',
      tag: 'existing-missing-engagement',
      linkedOpportunity: 'Fabrikam Security Modernization',
      status: 'active',
    },
    {
      id: '3',
      source: 'meeting',
      confidence: 78,
      title: 'Meeting transcript - Wipro collaboration on Northwind data analytics',
      date: 'April 15, 2025',
      account: 'Northwind Traders',
      partner: 'Wipro',
      revenue: '$2,100,000',
      explanation:
        'Meeting with Wipro representative discussing data warehouse modernization and Power BI implementation.',
      tag: 'new-opportunity',
      status: 'active',
    },
    {
      id: '4',
      source: 'email',
      confidence: 95,
      title: 'HCL Technologies engagement for Adventure Works Modern Work rollout',
      date: 'April 14, 2025',
      account: 'Adventure Works',
      partner: 'HCL Technologies',
      revenue: '$680,000',
      explanation:
        'Email exchange confirming HCL will provide change management services for M365 deployment.',
      tag: 'existing-missing-engagement',
      linkedOpportunity: 'Adventure Works M365 E5',
      status: 'active',
    },
    {
      id: '5',
      source: 'multiple',
      confidence: 88,
      title: 'TCS partnership signals for Woodgrove Bank modernization',
      date: 'April 13, 2025',
      account: 'Woodgrove Bank',
      partner: 'TCS',
      revenue: '$3,500,000',
      explanation:
        'Multiple communications across email and Teams mentioning TCS involvement in core banking system upgrade.',
      tag: 'new-opportunity',
      status: 'active',
    },
    {
      id: '6',
      source: 'chat',
      confidence: 64,
      title: 'Capgemini mentioned in Tailspin Toys discussions',
      date: 'April 12, 2025',
      account: 'Tailspin Toys',
      partner: 'Capgemini',
      revenue: '$420,000',
      explanation:
        'Brief mention of Capgemini possibly supporting supply chain solution deployment.',
      tag: 'new-opportunity',
      status: 'active',
    },
    {
      id: '7',
      source: 'email',
      confidence: 91,
      title: 'Deloitte co-sell on Litware cybersecurity initiative',
      date: 'April 11, 2025',
      account: 'Litware Inc',
      partner: 'Deloitte',
      revenue: '$1,750,000',
      explanation:
        'Detailed email thread with Deloitte partner discussing joint go-to-market for zero-trust security architecture.',
      tag: 'existing-missing-engagement',
      linkedOpportunity: 'Litware Zero Trust Implementation',
      status: 'active',
    },
    {
      id: '8',
      source: 'meeting',
      confidence: 82,
      title: 'Accenture Business Applications engagement for Proseware',
      date: 'April 10, 2025',
      account: 'Proseware Inc',
      partner: 'Accenture',
      revenue: '$950,000',
      explanation:
        'Meeting notes indicate Accenture will provide Dynamics 365 implementation services.',
      tag: 'new-opportunity',
      status: 'active',
    },
    {
      id: '9',
      source: 'email',
      confidence: 76,
      title: 'Infosys AI/ML partnership potential with Contoso',
      date: 'April 9, 2025',
      account: 'Contoso Ltd',
      partner: 'Infosys',
      revenue: '$1,100,000',
      explanation:
        'Email discussing Infosys data science team supporting Azure AI implementation.',
      tag: 'existing-missing-engagement',
      linkedOpportunity: 'Contoso AI Platform',
      status: 'active',
    },
  ]
}

export function generateTopOpportunities() {
  return [
    {
      name: 'Contoso Azure Cloud Migration',
      account: 'Contoso Ltd',
      dealValue: 2850000,
      closeDate: 'Jun 2025',
    },
    {
      name: 'Fabrikam Security Modernization',
      account: 'Fabrikam Inc',
      dealValue: 2150000,
      closeDate: 'Jul 2025',
    },
    {
      name: 'Northwind Data Analytics Platform',
      account: 'Northwind Traders',
      dealValue: 1920000,
      closeDate: 'May 2025',
    },
    {
      name: 'Woodgrove Banking Infrastructure',
      account: 'Woodgrove Bank',
      dealValue: 1750000,
      closeDate: 'Aug 2025',
    },
    {
      name: 'Adventure Works M365 E5',
      account: 'Adventure Works',
      dealValue: 1540000,
      closeDate: 'Apr 2025',
    },
    {
      name: 'Litware Zero Trust Implementation',
      account: 'Litware Inc',
      dealValue: 1420000,
      closeDate: 'Jun 2025',
    },
    {
      name: 'Tailspin Supply Chain Solution',
      account: 'Tailspin Toys',
      dealValue: 1180000,
      closeDate: 'Sep 2025',
    },
    {
      name: 'Proseware Dynamics 365 Rollout',
      account: 'Proseware Inc',
      dealValue: 980000,
      closeDate: 'May 2025',
    },
    {
      name: 'Contoso AI Platform',
      account: 'Contoso Ltd',
      dealValue: 875000,
      closeDate: 'Jul 2025',
    },
    {
      name: 'Fabrikam Modern Work Hub',
      account: 'Fabrikam Inc',
      dealValue: 720000,
      closeDate: 'Apr 2025',
    },
    {
      name: 'Northwind IoT Initiative',
      account: 'Northwind Traders',
      dealValue: 650000,
      closeDate: 'Aug 2025',
    },
    {
      name: 'Woodgrove Customer 360',
      account: 'Woodgrove Bank',
      dealValue: 580000,
      closeDate: 'Jun 2025',
    },
    {
      name: 'Adventure Works Analytics',
      account: 'Adventure Works',
      dealValue: 450000,
      closeDate: 'Sep 2025',
    },
    {
      name: 'Litware DevOps Transformation',
      account: 'Litware Inc',
      dealValue: 390000,
      closeDate: 'May 2025',
    },
    {
      name: 'Tailspin E-Commerce Platform',
      account: 'Tailspin Toys',
      dealValue: 280000,
      closeDate: 'Jul 2025',
    },
  ]
}

export function generatePipelineData(): PipelineItem[] {
  const statuses: PipelineItem['status'][] = [
    'active',
    'in-progress',
    'pending',
    'won',
    'lost',
  ]

  return [
    {
      id: '1',
      referralName: 'Accenture-Contoso Azure Migration',
      partner: 'Accenture',
      account: 'Contoso Ltd',
      opportunityName: 'Contoso Azure Cloud Migration',
      solutionArea: 'Azure Infrastructure',
      dealValue: 2850000,
      closeDate: '2025-06-30',
      status: 'in-progress',
    },
    {
      id: '2',
      referralName: 'Infosys-Fabrikam Security Initiative',
      partner: 'Infosys',
      account: 'Fabrikam Inc',
      opportunityName: 'Fabrikam Security Modernization',
      solutionArea: 'Security',
      dealValue: 2150000,
      closeDate: '2025-07-15',
      status: 'active',
    },
    {
      id: '3',
      referralName: 'Wipro-Northwind Data Platform',
      partner: 'Wipro',
      account: 'Northwind Traders',
      opportunityName: 'Northwind Data Analytics Platform',
      solutionArea: 'Data & AI',
      dealValue: 1920000,
      closeDate: '2025-05-20',
      status: 'in-progress',
    },
    {
      id: '4',
      referralName: 'TCS-Woodgrove Infrastructure',
      partner: 'TCS',
      account: 'Woodgrove Bank',
      opportunityName: 'Woodgrove Banking Infrastructure',
      solutionArea: 'Azure Infrastructure',
      dealValue: 1750000,
      closeDate: '2025-08-10',
      status: 'active',
    },
    {
      id: '5',
      referralName: 'HCL-Adventure M365 Deployment',
      partner: 'HCL Technologies',
      account: 'Adventure Works',
      opportunityName: 'Adventure Works M365 E5',
      solutionArea: 'Modern Work',
      dealValue: 1540000,
      closeDate: '2025-04-30',
      status: 'won',
    },
    {
      id: '6',
      referralName: 'Deloitte-Litware Zero Trust',
      partner: 'Deloitte',
      account: 'Litware Inc',
      opportunityName: 'Litware Zero Trust Implementation',
      solutionArea: 'Security',
      dealValue: 1420000,
      closeDate: '2025-06-15',
      status: 'in-progress',
    },
    {
      id: '7',
      referralName: 'Capgemini-Tailspin Supply Chain',
      partner: 'Capgemini',
      account: 'Tailspin Toys',
      opportunityName: 'Tailspin Supply Chain Solution',
      solutionArea: 'Business Applications',
      dealValue: 1180000,
      closeDate: '2025-09-05',
      status: 'pending',
    },
    {
      id: '8',
      referralName: 'Accenture-Proseware Dynamics',
      partner: 'Accenture',
      account: 'Proseware Inc',
      opportunityName: 'Proseware Dynamics 365 Rollout',
      solutionArea: 'Business Applications',
      dealValue: 980000,
      closeDate: '2025-05-25',
      status: 'active',
    },
    {
      id: '9',
      referralName: 'Infosys-Contoso AI Platform',
      partner: 'Infosys',
      account: 'Contoso Ltd',
      opportunityName: 'Contoso AI Platform',
      solutionArea: 'Data & AI',
      dealValue: 875000,
      closeDate: '2025-07-20',
      status: 'in-progress',
    },
    {
      id: '10',
      referralName: 'Wipro-Fabrikam Modern Work',
      partner: 'Wipro',
      account: 'Fabrikam Inc',
      opportunityName: 'Fabrikam Modern Work Hub',
      solutionArea: 'Modern Work',
      dealValue: 720000,
      closeDate: '2025-04-28',
      status: 'active',
    },
    {
      id: '11',
      referralName: 'TCS-Northwind IoT',
      partner: 'TCS',
      account: 'Northwind Traders',
      opportunityName: 'Northwind IoT Initiative',
      solutionArea: 'Azure Infrastructure',
      dealValue: 650000,
      closeDate: '2025-08-15',
      status: 'pending',
    },
    {
      id: '12',
      referralName: 'HCL-Woodgrove Customer 360',
      partner: 'HCL Technologies',
      account: 'Woodgrove Bank',
      opportunityName: 'Woodgrove Customer 360',
      solutionArea: 'Data & AI',
      dealValue: 580000,
      closeDate: '2025-06-30',
      status: 'in-progress',
    },
    {
      id: '13',
      referralName: 'Deloitte-Adventure Analytics',
      partner: 'Deloitte',
      account: 'Adventure Works',
      opportunityName: 'Adventure Works Analytics',
      solutionArea: 'Data & AI',
      dealValue: 450000,
      closeDate: '2025-09-10',
      status: 'active',
    },
    {
      id: '14',
      referralName: 'KPMG-Litware DevOps',
      partner: 'KPMG',
      account: 'Litware Inc',
      opportunityName: 'Litware DevOps Transformation',
      solutionArea: 'Azure Infrastructure',
      dealValue: 390000,
      closeDate: '2025-05-18',
      status: 'active',
    },
    {
      id: '15',
      referralName: 'Capgemini-Tailspin E-Commerce',
      partner: 'Capgemini',
      account: 'Tailspin Toys',
      opportunityName: 'Tailspin E-Commerce Platform',
      solutionArea: 'Business Applications',
      dealValue: 280000,
      closeDate: '2025-07-25',
      status: 'pending',
    },
    {
      id: '16',
      referralName: 'Accenture-Contoso Security Audit',
      partner: 'Accenture',
      account: 'Contoso Ltd',
      opportunityName: 'Contoso Security Assessment',
      solutionArea: 'Security',
      dealValue: 220000,
      closeDate: '2025-05-05',
      status: 'lost',
    },
    {
      id: '17',
      referralName: 'Infosys-Fabrikam Cloud Assessment',
      partner: 'Infosys',
      account: 'Fabrikam Inc',
      opportunityName: 'Fabrikam Cloud Readiness',
      solutionArea: 'Azure Infrastructure',
      dealValue: 180000,
      closeDate: '2025-04-15',
      status: 'won',
    },
    {
      id: '18',
      referralName: 'Wipro-Northwind Compliance',
      partner: 'Wipro',
      account: 'Northwind Traders',
      opportunityName: 'Northwind Compliance Platform',
      solutionArea: 'Security',
      dealValue: 340000,
      closeDate: '2025-06-20',
      status: 'in-progress',
    },
  ]
}
